language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t douglaszickuhr/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true douglaszickuhr/docker-test npm test

after_success:
  - docker build -t douglaszickuhr/multi-client -f ./client
  - docker build -t douglaszickuhr/multi-nginx -f ./nginx
  - docker build -t douglaszickuhr/multi-server -f ./server
  - docker build -t douglaszickuhr/multi-worker -f ./worker
  # Log in to Docker CLI
  - echo "$docker_password" | docker login -u "docker_user" --password-stdin
  - docker push douglaszickuhr/multi-client
  - docker push douglaszickuhr/multi-nginx
  - docker push douglaszickuhr/multi-server
  - docker push douglaszickuhr/multi-worker
